import json
import subprocess
from pathlib import Path
from typing import Any


def write_probe_placeholder(path: Path, probe_plan: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    target = probe_plan.get("target_location", {})
    path.write_text(
        "# BTCR probe placeholder.\n"
        "# The final probe/final test is generated by the AssertFlip LLM prompt.\n"
        f"# Target: {target.get('file', '')}:{target.get('line', '')}\n\n"
        "def test_btcr_probe_placeholder():\n"
        "    pass\n"
    )


def validate_probe_test(
    *,
    probe_path: Path,
    tests_dir: Path,
    pytest_cmd: str = "pytest",
    target_file: str = "",
    target_line: int | None = None,
) -> dict[str, Any]:
    result = {
        "probe_path": str(probe_path),
        "target_file": target_file,
        "target_line": target_line,
        "status": "skipped",
        "failure_type": None,
        "commands": [],
        "coverage": None,
    }
    if not probe_path.exists():
        result.update({"status": "skipped", "reason": "probe file does not exist"})
        return result

    commands = [
        ["python", "-m", "py_compile", str(probe_path)],
        [*pytest_cmd.split(), "--collect-only", str(probe_path)],
        [*pytest_cmd.split(), str(probe_path)],
    ]
    for command in commands:
        proc = subprocess.run(command, cwd=str(tests_dir), capture_output=True, text=True, timeout=120)
        entry = {
            "command": command,
            "returncode": proc.returncode,
            "stdout": proc.stdout[-4000:],
            "stderr": proc.stderr[-4000:],
        }
        result["commands"].append(entry)
        if proc.returncode != 0:
            result.update({"status": "failed", "failure_type": "Environment Error"})
            return result

    result.update({
        "status": "passed",
        "failure_type": None,
        "note": "Target-line coverage is not enforced for the placeholder probe in the minimal BTCR integration.",
    })
    return result


def save_probe_validation(path: Path, result: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(result, indent=2, ensure_ascii=False))
