#!/usr/bin/env bash
set -euo pipefail

CONTRACT_BRT_ROOT="${CONTRACT_BRT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
export CONTRACT_BRT_ROOT
export CONTRACT_BRT_ENABLE="${CONTRACT_BRT_ENABLE:-1}"
export CONTRACT_BRT_CONTRACT_DIR="${CONTRACT_BRT_CONTRACT_DIR:-$CONTRACT_BRT_ROOT/contracts}"
export CONTRACT_BRT_GENERATED_TEST_DIR="${CONTRACT_BRT_GENERATED_TEST_DIR:-$CONTRACT_BRT_ROOT/generated_tests}"
export CONTRACT_BRT_SCAFFOLD_MODE="${CONTRACT_BRT_SCAFFOLD_MODE:-off}"
export CONTRACT_BRT_PROMPT_MODE="${CONTRACT_BRT_PROMPT_MODE:-reactive}"
export CONTRACT_BRT_INCLUDE_SCAFFOLD_IN_PROMPT="${CONTRACT_BRT_INCLUDE_SCAFFOLD_IN_PROMPT:-0}"
export CONTRACT_BRT_STRICTNESS="${CONTRACT_BRT_STRICTNESS:-warn}"
export CONTRACT_BRT_PREFLIGHT_MODE="${CONTRACT_BRT_PREFLIGHT_MODE:-syntax}"
export PYTHONPATH="$CONTRACT_BRT_ROOT:$CONTRACT_BRT_ROOT/assertflip_contract/src${PYTHONPATH:+:$PYTHONPATH}"

mkdir -p \
  "$CONTRACT_BRT_ROOT/logs" \
  "$CONTRACT_BRT_ROOT/results" \
  "$CONTRACT_BRT_CONTRACT_DIR" \
  "$CONTRACT_BRT_GENERATED_TEST_DIR"

for required in "$CONTRACT_BRT_ROOT/ecg" "$CONTRACT_BRT_ROOT/assertflip_contract" "$CONTRACT_BRT_ROOT/datasets"; do
  if [[ ! -e "$required" ]]; then
    echo "Missing required Contract-BRT path: $required" >&2
    exit 2
  fi
done

echo "Contract-BRT workspace ready"
echo "CONTRACT_BRT_ROOT=$CONTRACT_BRT_ROOT"
echo "CONTRACT_BRT_CONTRACT_DIR=$CONTRACT_BRT_CONTRACT_DIR"
echo "CONTRACT_BRT_GENERATED_TEST_DIR=$CONTRACT_BRT_GENERATED_TEST_DIR"
echo "CONTRACT_BRT_SCAFFOLD_MODE=$CONTRACT_BRT_SCAFFOLD_MODE"
echo "CONTRACT_BRT_PROMPT_MODE=$CONTRACT_BRT_PROMPT_MODE"
echo "CONTRACT_BRT_INCLUDE_SCAFFOLD_IN_PROMPT=$CONTRACT_BRT_INCLUDE_SCAFFOLD_IN_PROMPT"
echo "CONTRACT_BRT_STRICTNESS=$CONTRACT_BRT_STRICTNESS"
echo "CONTRACT_BRT_PREFLIGHT_MODE=$CONTRACT_BRT_PREFLIGHT_MODE"
